# ΘΑ ΓΙΝΕΙ ΜΙΑ ΠΡΩΤΗ ΠΡΟΣΕΓΓΙΣΗ ΜΕ ΟΛΑ ΤΑ ΔΕΔΟΜΕΝΑ ΠΟΥ ΕΧΩ ΝΑ ΔΟΥΜΕ ΠΩς ΔΟΥΛΕΥΟΝ ΑΛΛΑ ΜΑΛΛΟΝ ΘΑ ΚΑΤΑΛΗΞΟΥΜΕ ΝΑ ΠΑΙΞΟΥΜΕ ΜΟΝΟ ΜΕ FIGHTERS

In [3]:
import pandas as pd
import numpy as np

import pandas as pd
import numpy as np

In [5]:
fights = pd.read_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\fights_training.csv')
fight_details = pd.read_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\fight_details_training.csv')
events = pd.read_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\events_training.csv')
fighters = pd.read_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\fighters_training.csv')

In [21]:
fights.head(1)

,fight_id,round_num,event_id,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,fighter1_id,fighter2_id,winner_id,weight_class_encoded,method_detailed_encoded,method_basic_encoded,total_seconds
0,1,1,1,0,0,1,0,1,0,1,0,10,1,10,0,0,0,20

In [22]:
fight_details.head(1)

,fight_id,fighter1_id,fighter2_id,fighter1_sig_str_total,fighter2_sig_str_total,fighter1_head_total,fighter2_head_total,fighter1_body_total,fighter2_body_total,fighter1_leg_total,fighter2_leg_total,fighter1_distance_total,fighter2_distance_total,fighter1_clinch_total,fighter2_clinch_total,fighter1_ground_total,fighter2_ground_total,fighter1_percent_sign,fighter2_percent_sign
0,1,10,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1.0,0.0

In [23]:
fights_fights_det.columns

Index(['fight_id', 'round_num', 'event_id', 'fighter1_kd', 'fighter2_kd',
       'fighter1_strikes', 'fighter2_strikes', 'fighter1_td', 'fighter2_td',
       'fighter1_sub', 'fighter2_sub', 'fighter1_id_x', 'fighter2_id_x',
       'winner_id', 'weight_class_encoded', 'method_detailed_encoded',
       'method_basic_encoded', 'total_seconds', 'fighter1_id_y',
       'fighter2_id_y', 'fighter1_sig_str_total', 'fighter2_sig_str_total',
       'fighter1_head_total', 'fighter2_head_total', 'fighter1_body_total',
       'fighter2_body_total', 'fighter1_leg_total', 'fighter2_leg_total',
       'fighter1_distance_total', 'fighter2_distance_total',
       'fighter1_clinch_total', 'fighter2_clinch_total',
       'fighter1_ground_total', 'fighter2_ground_total',
       'fighter1_percent_sign', 'fighter2_percent_sign'],
      dtype='str')

In [24]:
fights_fights_det = pd.merge(fights,fight_details,left_on ='fight_id',right_on='fight_id')

In [25]:
events.head(1)

,id,main_card,event_year,event_day,country_encoded,month_encoded,city_encoded,region_encoded
0,1,True,1994,11,0,3,0,0

In [26]:
fights_fights_det_events = pd.merge(fights_fights_det , events ,left_on ='event_id',right_on='id')

In [27]:
fights_fights_det_events.columns

Index(['fight_id', 'round_num', 'event_id', 'fighter1_kd', 'fighter2_kd',
       'fighter1_strikes', 'fighter2_strikes', 'fighter1_td', 'fighter2_td',
       'fighter1_sub', 'fighter2_sub', 'fighter1_id_x', 'fighter2_id_x',
       'winner_id', 'weight_class_encoded', 'method_detailed_encoded',
       'method_basic_encoded', 'total_seconds', 'fighter1_id_y',
       'fighter2_id_y', 'fighter1_sig_str_total', 'fighter2_sig_str_total',
       'fighter1_head_total', 'fighter2_head_total', 'fighter1_body_total',
       'fighter2_body_total', 'fighter1_leg_total', 'fighter2_leg_total',
       'fighter1_distance_total', 'fighter2_distance_total',
       'fighter1_clinch_total', 'fighter2_clinch_total',
       'fighter1_ground_total', 'fighter2_ground_total',
       'fighter1_percent_sign', 'fighter2_percent_sign', 'id', 'main_card',
       'event_year', 'event_day', 'country_encoded', 'month_encoded',
       'city_encoded', 'region_encoded'],
      dtype='str')

In [28]:
fighters.head(1)

,wins,losses,draws,SLpM,SApM,TD Avg.,Sub. Avg.,ID,height,weight_kg,Str. Acc._total,Str. Def_total,TD Acc._total,TD Def._total,reach_cm,stance,age
0,0,2,0,0.0,0.0,0.0,0.0,1,182.88,79.38,0.0,0.0,0.0,0.0,180.34,0,50

In [29]:
fights_fights_det_events_fight1 = pd.merge(fights_fights_det_events , fighters , left_on='fighter1_id_x',right_on = 'ID')
fights_fights_det_events_fight1_fight2 = pd.merge(fights_fights_det_events_fight1 , fighters , left_on='fighter2_id_x',right_on = 'ID')

In [30]:
fights_fights_det_events_fight1_fight2.columns

Index(['fight_id', 'round_num', 'event_id', 'fighter1_kd', 'fighter2_kd',
       'fighter1_strikes', 'fighter2_strikes', 'fighter1_td', 'fighter2_td',
       'fighter1_sub', 'fighter2_sub', 'fighter1_id_x', 'fighter2_id_x',
       'winner_id', 'weight_class_encoded', 'method_detailed_encoded',
       'method_basic_encoded', 'total_seconds', 'fighter1_id_y',
       'fighter2_id_y', 'fighter1_sig_str_total', 'fighter2_sig_str_total',
       'fighter1_head_total', 'fighter2_head_total', 'fighter1_body_total',
       'fighter2_body_total', 'fighter1_leg_total', 'fighter2_leg_total',
       'fighter1_distance_total', 'fighter2_distance_total',
       'fighter1_clinch_total', 'fighter2_clinch_total',
       'fighter1_ground_total', 'fighter2_ground_total',
       'fighter1_percent_sign', 'fighter2_percent_sign', 'id', 'main_card',
       'event_year', 'event_day', 'country_encoded', 'month_encoded',
       'city_encoded', 'region_encoded', 'wins_x', 'losses_x', 'draws_x',
       'SLpM_x', 'SApM_x', 'TD Avg._x', 'Sub. Avg._x', 'ID_x', 'height_x',
       'weight_kg_x', 'Str. Acc._total_x', 'Str. Def_total_x',
       'TD Acc._total_x', 'TD Def._total_x', 'reach_cm_x', 'stance_x', 'age_x',
       'wins_y', 'losses_y', 'draws_y', 'SLpM_y', 'SApM_y', 'TD Avg._y',
       'Sub. Avg._y', 'ID_y', 'height_y', 'weight_kg_y', 'Str. Acc._total_y',
       'Str. Def_total_y', 'TD Acc._total_y', 'TD Def._total_y', 'reach_cm_y',
       'stance_y', 'age_y'],
      dtype='str')

In [32]:
fights_fights_det_events_fight1_fight2.drop(columns=['fighter1_id_y','fighter2_id_y'],inplace=True)
data = fights_fights_det_events_fight1_fight2.copy()

In [34]:
data.to_csv('all_joined.csv',index=False)

In [35]:
data = data.rename(columns={
    'fighter1_id_x': 'fighter1_id',
    'fighter2_id_x': 'fighter2_id'
})

In [41]:
# οκ τα φέραμε όλα να δούμε πως είναι αλλά τα περισότερα είναι άχρηστα στο μοντέλο

# Παμε μόνο με fighters

In [6]:
fights.shape[0]

8680

In [7]:
fights.head(1)

,fight_id,round_num,event_id,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,fighter1_id,fighter2_id,winner_id,weight_class_encoded,method_detailed_encoded,method_basic_encoded,total_seconds
0,1,1,1,0,0,1,0,1,0,1,0,10,1,10,0,0,0,20

In [8]:
data = fights[['fighter1_id','fighter2_id','winner_id']]

In [9]:
data = pd.merge(data,fighters,left_on='fighter1_id',right_on='ID')
data = pd.merge(data,fighters,left_on='fighter2_id',right_on='ID')

In [10]:
data.columns

Index(['fighter1_id', 'fighter2_id', 'winner_id', 'wins_x', 'losses_x',
       'draws_x', 'SLpM_x', 'SApM_x', 'TD Avg._x', 'Sub. Avg._x', 'ID_x',
       'height_x', 'weight_kg_x', 'Str. Acc._total_x', 'Str. Def_total_x',
       'TD Acc._total_x', 'TD Def._total_x', 'reach_cm_x', 'stance_x', 'age_x',
       'wins_y', 'losses_y', 'draws_y', 'SLpM_y', 'SApM_y', 'TD Avg._y',
       'Sub. Avg._y', 'ID_y', 'height_y', 'weight_kg_y', 'Str. Acc._total_y',
       'Str. Def_total_y', 'TD Acc._total_y', 'TD Def._total_y', 'reach_cm_y',
       'stance_y', 'age_y'],
      dtype='str')

In [69]:
data['wins_diff'] = data['wins_x'] - data['wins_y']
data['losses_diff'] = data['losses_x'] - data['losses_y']
data['draws_diff'] = data['draws_x'] - data['draws_y']

data['slpm_diff'] = data['SLpM_x'] - data['SLpM_y']
data['sapm_diff'] = data['SApM_x'] - data['SApM_y']
data['td_avg_diff'] = data['TD Avg._x'] - data['TD Avg._y']
data['sub_avg_diff'] = data['Sub. Avg._x'] - data['Sub. Avg._y']

data['height_diff'] = data['height_x'] - data['height_y']
data['weight_diff'] = data['weight_kg_x'] - data['weight_kg_y']
data['reach_diff'] = data['reach_cm_x'] - data['reach_cm_y']
data['age_diff'] = data['age_x'] - data['age_y']

data['str_acc_diff'] = data['Str. Acc._total_x'] - data['Str. Acc._total_y']
data['str_def_diff'] = data['Str. Def_total_x'] - data['Str. Def_total_y']
data['td_acc_diff'] = data['TD Acc._total_x'] - data['TD Acc._total_y']

In [70]:
data['same_stance'] = (data['stance_x'] == data['stance_y']).astype(int)

In [71]:
data = data.drop(columns=[
    'wins_x','losses_x','draws_x',
    'SLpM_x','SApM_x','TD Avg._x','Sub. Avg._x',
    'height_x','weight_kg_x','reach_cm_x','age_x',
    'Str. Acc._total_x','Str. Def_total_x','TD Acc._total_x',

    'wins_y','losses_y','draws_y',
    'SLpM_y','SApM_y','TD Avg._y','Sub. Avg._y',
    'height_y','weight_kg_y','reach_cm_y','age_y',
    'Str. Acc._total_y','Str. Def_total_y','TD Acc._total_y',

    'stance_x','stance_y'
])

In [72]:
data

,fighter1_id,fighter2_id,winner_id,ID_x,TD Def._total_x,ID_y,TD Def._total_y,wins_diff,losses_diff,draws_diff,...,sub_avg_diff,height_diff,weight_diff,reach_diff,age_diff,str_acc_diff,str_def_diff,td_acc_diff,td_def_diff,same_stance
0,10,1,10,10,0.00,1,0.00,2,-1,0,...,0.0,-5.08,15.87,0.00,-24,0.00,0.00,0.00,0.00,0
1,30,2,30,30,0.00,2,0.00,20,16,0,...,0.0,12.70,22.68,0.00,36,0.00,0.00,0.00,0.00,0
2,13,3,13,13,0.00,3,0.00,1,-2,0,...,0.0,-12.70,-29.49,0.00,0,0.00,0.00,0.00,0.00,0
3,5,4,5,5,0.00,4,0.00,1,-1,0,...,0.0,-15.24,-15.87,0.00,0,0.00,0.00,0.00,0.00,1
4,12,6,12,12,0.00,6,0.00,1,4,0,...,0.0,-10.16,-34.02,0.00,34,0.00,0.00,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8675,1996,2229,1996,1996,0.76,2229,0.71,3,-1,0,...,0.8,-7.62,0.00,-12.70,-2,0.16,-0.03,0.29,0.05,1
8676,2316,2674,2316,2316,0.82,2674,0.00,12,2,0,...,0.1,-5.08,0.00,-5.08,5,-0.07,-0.05,0.66,0.82,0
8677,2673,2255,2673,2673,0.00,2255,0.46,6,-1,1,...,0.8,-5.08,0.00,-5.08,-4,-0.14,0.07,0.50,-0.46,0
8678,1979,2183,1979,1979,0.59,2183,0.73,3,1,1,...,0.5,7.62,0.00,7.62,4,0.15,0.07,0.20,-0.14,1
8679,2322,2393,2322,2322,0.73,2393,0.50,-5,-4,0,...,-0.5,-5.08,0.00,-2.54,3,-0.04,0.10,0.25,0.23,1

In [73]:
data.isnull().sum()

fighter1_id        0
fighter2_id        0
winner_id          0
ID_x               0
TD Def._total_x    0
ID_y               0
TD Def._total_y    0
wins_diff          0
losses_diff        0
draws_diff         0
slpm_diff          0
sapm_diff          0
td_avg_diff        0
sub_avg_diff       0
height_diff        0
weight_diff        0
reach_diff         0
age_diff           0
str_acc_diff       0
str_def_diff       0
td_acc_diff        0
td_def_diff        0
same_stance        0
dtype: int64

In [80]:
data['target'] = (data['winner_id'] == data['fighter1_id']).astype(int)
y = data['target']
X = data.drop(columns=['winner_id', 'fighter1_id', 'fighter2_id', 'target'])

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

In [82]:
from xgboost import XGBClassifier

In [83]:
model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [84]:
prob = model.predict_proba(X_test)

In [85]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [86]:
import pandas as pd

results = pd.DataFrame({
    'actual': y_test.values,
    'predicted': y_pred,
    'prob_fighter1_win': y_prob
})

print(results.head(20))

    actual  predicted  prob_fighter1_win
0        1          1           0.996861
1        1          1           0.997331
2        1          1           0.994863
3        1          1           0.997215
4        1          1           0.945161
5        1          1           0.983721
6        1          1           0.996908
7        1          1           0.995274
8        1          1           0.999508
9        1          1           0.997173
10       1          1           0.952610
11       1          1           0.999450
12       1          1           0.984310
13       1          1           0.994178
14       1          1           0.997210
15       1          1           0.997734
16       1          1           0.993969
17       1          1           0.996343
18       1          1           0.996096
19       1          1           0.997737

In [87]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9890552995391705

In [88]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   0   19]
 [   0 1717]]

In [89]:
correct = (results['actual'] == results['predicted']).sum()
total = len(results)

print("Correct:", correct)
print("Total:", total)
print("Accuracy manual:", correct / total)

Correct: 1717
Total: 1736
Accuracy manual: 0.9890552995391705

In [ ]:
# τα δεδομένα μας επιρεάζουν , για να φτάσουμε σε σημέιο να κάνουμε πρόβλεψη των νικιτή θέλουμε διαφορετικά και αλλα δεδομένα