In [1]:
import pyodbc

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=MSI\SQLE22;"
    r"DATABASE=UFC;"
    r"Trusted_Connection=yes;"
)

print("CONNECTED")

CONNECTED

In [2]:
import pandas as pd

query = 'select * from events'

data = pd.read_sql(query,conn)

C:\Users\mplan\AppData\Local\Temp\ipykernel_25056\1585671333.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query,conn)

In [5]:
data.head(1)

,id,event_name,main_card,event_year,country,event_month,event_day,city,region,event_url
0,1,UFC 2: No Way Out,True,1994,USA,March,11,Denver,Colorado,http://ufcstats.com/event-details/a6a9ab5a824e...

In [ ]:
data.isnull().sum() # no nulls thats good

id             0
event_name     0
main_card      0
event_year     0
country        0
event_month    0
event_day      0
city           0
region         0
event_url      0
dtype: int64

In [8]:
data.columns

Index(['id', 'event_name', 'main_card', 'event_year', 'country', 'event_month',
       'event_day', 'city', 'region', 'event_url'],
      dtype='str')

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 774 entries, 0 to 773
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           774 non-null    int64
 1   event_name   774 non-null    str
 2   main_card    774 non-null    bool
 3   event_year   774 non-null    int64
 4   country      774 non-null    str
 5   event_month  774 non-null    str
 6   event_day    774 non-null    int64
 7   city         774 non-null    str
 8   region       774 non-null    str
 9   event_url    774 non-null    str
dtypes: bool(1), int64(3), str(6)
memory usage: 55.3 KB

In [10]:
## απο τα δεδομένα βλεπω ότι για να προετοιμασω τα δεδομένα για μοντέλο θα χρειαστεί να κρατήσω μόνο τα σημαντικά
# και να κάνω μαπινγκ τους μηνες την χώρα και την περιοχή αλλά να τα κρατήσω για μελλοντικά νέα δεδομένα 
# άρα θα φτιάξω ένα json maping να το έχω και θα το ρίχνω και στα νέα δεδομένα που θα κάνω προβλέψεια αργότερα στο μοντέλο

## preparation from now on

In [ ]:
# τώρα θα φτιάξω μάπινγκ για τις χώρες και θα το περάσω σαν νέα στήλη

In [ ]:
country_mapping = {}

for i, country in enumerate(data['country'].unique()):
    country_mapping[country] = i


data['country_encoded'] = data['country'].map(country_mapping)

In [ ]:
## country οκ πάμε για μήνες τώρα

In [ ]:
month_mapping = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}


data['month_encoded'] =  data['event_month'].map(month_mapping)

In [35]:
## πάμε τώρα πόλη

In [ ]:
city_mapping = {}

for i, city in enumerate(data['city'].unique()):
    city_mapping[city] = i






data['city_encoded']  = data['city'].map(city_mapping)

In [41]:
# ΤΏΡΑ ΤΑ REGION

In [ ]:
region_mapping = {}

for i, reg in enumerate(data['region'].unique()):
    region_mapping[reg] = i

import json 




data['region_encoded']  = data['region'].map(region_mapping)

In [ ]:
## είμαστε οκ 

## κάνω save τα mappings

with open(r"C:\Users\mplan\Desktop\ufc\MAPPINGS\country_mapping.json", "w") as f:
    json.dump(country_mapping, f, indent=4)


with open(r"C:\Users\mplan\Desktop\ufc\MAPPINGS\month_mapping.json", "w") as f:
    json.dump(month_mapping , f ,indent=4)

with open(r"C:\Users\mplan\Desktop\ufc\MAPPINGS\city_mapping.json", "w") as f:
    json.dump(city_mapping, f, indent=4)

with open(r"C:\Users\mplan\Desktop\ufc\MAPPINGS\region_mapping.json", "w") as f:
    json.dump(region_mapping, f, indent=4)

In [44]:
data.head(1)

,id,event_name,main_card,event_year,country,event_month,event_day,city,region,event_url,country_encoded,month_encoded,city_encoded,region_encoded
0,1,UFC 2: No Way Out,True,1994,USA,March,11,Denver,Colorado,http://ufcstats.com/event-details/a6a9ab5a824e...,0,3,0,0

In [46]:
# κάνω export τα δεδομένα για το training 
data_clear = data.drop(columns=['event_name','country','event_month','city','region','event_url'])

In [48]:
data_clear.to_csv(r'C:\Users\mplan\Desktop\ufc\TRAINING_DATA\events_training.csv',index=False)

In [ ]:
## γενικα τα events εχουν την λιγότερη επίδραση στο mats παρόλα αυτά εμείς θα τα κρατήσουμε και βλέπουμε