In [1]:
import pandas as pd
import numpy as np

In [2]:
fighters = pd.read_csv('fighters_correct_with_id.csv')
fights = pd.read_csv('fights.csv')
detail_fights = pd.read_csv('fight_details.csv')
events = pd.read_csv('events.csv')

In [3]:
fighters.head(1)

,url,name,nickname,record,wins,losses,draws,Height,Weight,Reach,...,DOB,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,ID
0,http://ufcstats.com/fighter-details/767755fd74...,Khamzat Chimaev,Borz,15-1-0,15,1,0.0,"6' 2""",185 lbs.,"75""",...,"May 01, 1994",4.01,54%,2.98,52%,5.32,58%,87%,1.4,2672

In [4]:
fights.head(2)

,fight_id,fight_url,fighter_1,fighter_2,winner,weight_class,method,round,time,event_name,event_id,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub
0,8688,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Sean Strickland,Middleweight,S-DEC,5,5:00,UFC 328: Chimaev vs. Strickland,773,0.0,0.0,123.0,98.0,0.0,9.0,0.0,0.0
1,8687,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Joshua Van,Flyweight,KO/TKO Punches,5,1:32,UFC 328: Chimaev vs. Strickland,773,2.0,0.0,131.0,55.0,1.0,8.0,2.0,0.0

# we make first the df fights

In [5]:
fighters1 = fights['fighter_1']
fighters2 = fights['fighter_2']

fighters_id = fighters['ID']
fighters_names = fighters['name']

fighter_name_id = {
    fighters_names[i]: int(fighters_id[i])
    for i in range(len(fighters_id))
}

fighter1_id = []
fighter2_id = []

for i in range(len(fighters1)):
    fighter1_id.append(fighter_name_id.get(fighters1[i]))
    fighter2_id.append(fighter_name_id.get(fighters2[i]))

In [6]:
len(fighters1),len(fighter1_id)

(8688, 8688)

In [7]:
for i in range(10):
    print(fighter1_id[i],fighters1[i],fighter2_id[i],fighters2[i])

2671 Sean Strickland 2672 Khamzat Chimaev
2670 Joshua Van 2669 Tatsuro Taira
2668 Alexander Volkov 2667 Waldo Cortes Acosta
2666 Sean Brady 2665 Joaquin Buckley
2664 King Green 2663 Jeremy Stephens
2662 Ateba Gautier 2661 Ozzy Diaz
2659 Yaroslav Amosov 2660 Joel Alvarez
2658 Grant Dawson 2657 Mateusz Rebecki
2656 Jim Miller 2655 Jared Gordon
2654 Roman Kopylov 2653 Marco Tulio

In [8]:
fighter1_id = pd.Series(fighter1_id).astype('Int64')
fighter2_id = pd.Series(fighter2_id).astype('Int64')


fights['fighter1_id'] = fighter1_id
fights['fighter2_id'] = fighter2_id

fights.head(3)

,fight_id,fight_url,fighter_1,fighter_2,winner,weight_class,method,round,time,event_name,...,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,fighter1_id,fighter2_id
0,8688,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Sean Strickland,Middleweight,S-DEC,5,5:00,UFC 328: Chimaev vs. Strickland,...,0.0,0.0,123.0,98.0,0.0,9.0,0.0,0.0,2671,2672
1,8687,http://ufcstats.com/fight-details/c85b53086114...,Joshua Van,Tatsuro Taira,Joshua Van,Flyweight,KO/TKO Punches,5,1:32,UFC 328: Chimaev vs. Strickland,...,2.0,0.0,131.0,55.0,1.0,8.0,2.0,0.0,2670,2669
2,8686,http://ufcstats.com/fight-details/22ba4f1b0aaf...,Alexander Volkov,Waldo Cortes Acosta,Alexander Volkov,Heavyweight,U-DEC,3,5:00,UFC 328: Chimaev vs. Strickland,...,0.0,0.0,88.0,54.0,0.0,0.0,0.0,0.0,2668,2667

In [9]:
fights.to_csv('fights.csv',index=False)

## twra oame na perasoyme to fight_id sta fight_details

In [10]:
detail_fights.shape[0], fights.shape[0]

(8659, 8688)

In [11]:
fights.head(1)

,fight_id,fight_url,fighter_1,fighter_2,winner,weight_class,method,round,time,event_name,...,fighter1_kd,fighter2_kd,fighter1_strikes,fighter2_strikes,fighter1_td,fighter2_td,fighter1_sub,fighter2_sub,fighter1_id,fighter2_id
0,8688,http://ufcstats.com/fight-details/70f1621080b3...,Sean Strickland,Khamzat Chimaev,Sean Strickland,Middleweight,S-DEC,5,5:00,UFC 328: Chimaev vs. Strickland,...,0.0,0.0,123.0,98.0,0.0,9.0,0.0,0.0,2671,2672

In [19]:
fight_url = fights['fight_url']
fight_id = fights['fight_id']

fight_url_id = {
    fight_url[i]: int(fight_id[i])
    for i in range(len(fight_id))
}


fight_id_ = []

for i in range(len(fight_url)):
    fight_id_.append(fight_url_id.get(fight_url[i]))

In [20]:
for i in range(5):
    print(fight_id[i] ,fight_url[i], fight_id_[i])

8688 http://ufcstats.com/fight-details/70f1621080b3435c 8688
8687 http://ufcstats.com/fight-details/c85b530861145935 8687
8686 http://ufcstats.com/fight-details/22ba4f1b0aafbf82 8686
8685 http://ufcstats.com/fight-details/845b8653f9cf839c 8685
8684 http://ufcstats.com/fight-details/1158a27a1a04b971 8684

In [ ]:
# έγιναν και τα υπόλοιπα αλλά διστυχώς δεν εγινε save και τα χάσαμε αλλα με την ίδια λογική περνάω και στα fight_Details τα id απο τους μαχητές