In [14]:
import pandas as pd

data = pd.read_csv('ufc_fighter_links.csv')
data = data['fighter_url'].tolist()

data[:12]

['http://ufcstats.com/fighter-details/767755fd74662dbf',
 'http://ufcstats.com/fighter-details/0d8011111be000b2',
 'http://ufcstats.com/fighter-details/17e97649403ba428',
 'http://ufcstats.com/fighter-details/4461d7e47375a895',
 'http://ufcstats.com/fighter-details/279566840aa55bf2',
 'http://ufcstats.com/fighter-details/fc08099550072fe4',
 'http://ufcstats.com/fighter-details/45f7cb591c3ab00b',
 'http://ufcstats.com/fighter-details/b9437600497350f3',
 'http://ufcstats.com/fighter-details/887961364be5ceb3',
 'http://ufcstats.com/fighter-details/18968f97ad34f15c',
 'http://ufcstats.com/fighter-details/2f815ed5f8278ba6',
 'http://ufcstats.com/fighter-details/6967153c7edb4d87']

In [15]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time


headers = {
    "User-Agent": "Mozilla/5.0"
}


fighter_links = data


results = []


for i, url in enumerate(fighter_links):

    try:

        r = requests.get(url, headers=headers, timeout=10)

        soup = BeautifulSoup(r.text, "html.parser")



        name_tag = soup.select_one(".b-content__title-highlight")

        name = name_tag.text.strip() if name_tag else None

        nickname_tag = soup.select_one(".b-content__Nickname")

        nickname = nickname_tag.text.strip() if nickname_tag else None

   

        record_tag = soup.select_one(".b-content__title-record")

        record_text = record_tag.text.strip() if record_tag else ""

        record = record_text.replace("Record:", "").strip()

        wins = None
        losses = None
        draws = None

        try:
            wins, losses, draws = record.split("-")
        except:
            pass

        info = {}

        rows = soup.select(".b-list__box-list-item")

        for row in rows:

            text = row.text.strip().replace("\n", "")

            if ":" in text:

                key, value = text.split(":", 1)

                info[key.strip()] = value.strip()


        fighter_data = {
            "url": url,
            "name": name,
            "nickname": nickname,
            "record": record,
            "wins": wins,
            "losses": losses,
            "draws": draws,
        }

        # προσθέτει όλα τα stats/info
        fighter_data.update(info)

        # append row
        results.append(fighter_data)

        print(f"{i+1}/{len(fighter_links)} DONE -> {name}")

        time.sleep(0.5)

    except Exception as e:

        print(f"\nERROR AT {url}")
        print(e)


fighters_df = pd.DataFrame(results)



fighters_df[['wins', 'losses', 'draws']] = (
    fighters_df[['wins', 'losses', 'draws']]
    .apply(pd.to_numeric, errors='coerce')
)



print(fighters_df.head())

1/2672 DONE -> Khamzat Chimaev
2/2672 DONE -> Sean Strickland
3/2672 DONE -> Joshua Van
4/2672 DONE -> Tatsuro Taira
5/2672 DONE -> Alexander Volkov
6/2672 DONE -> Waldo Cortes Acosta
7/2672 DONE -> Sean Brady
8/2672 DONE -> Joaquin Buckley
9/2672 DONE -> King Green
10/2672 DONE -> Jeremy Stephens
11/2672 DONE -> Ateba Gautier
12/2672 DONE -> Ozzy Diaz
13/2672 DONE -> Joel Alvarez
14/2672 DONE -> Yaroslav Amosov
15/2672 DONE -> Grant Dawson
16/2672 DONE -> Mateusz Rebecki
17/2672 DONE -> Jim Miller
18/2672 DONE -> Jared Gordon
19/2672 DONE -> Roman Kopylov
20/2672 DONE -> Marco Tulio
21/2672 DONE -> Pat Sabatini
22/2672 DONE -> William Gomis
23/2672 DONE -> Baisangur Susurkaev
24/2672 DONE -> Djorden Santos
25/2672 DONE -> Clayton Carpenter
26/2672 DONE -> Jose Ochoa
27/2672 DONE -> Jack Della Maddalena
28/2672 DONE -> Carlos Prates
29/2672 DONE -> Beneil Dariush
30/2672 DONE -> Quillan Salkilld
31/2672 DONE -> Tim Elliott
32/2672 DONE -> Steve Erceg
33/2672 DONE -> Marwan Rahiki
34/2672 DONE -> Ollie Schmid
35/2672 DONE -> Shamil Gaziev
36/2672 DONE -> Brando Pericic
37/2672 DONE -> Tai Tuivasa
38/2672 DONE -> Louie Sutherland
39/2672 DONE -> Cam Rowston
40/2672 DONE -> Robert Bryczek
41/2672 DONE -> Junior Tafa
42/2672 DONE -> Kevin Christian
43/2672 DONE -> Jacob Malkoun
44/2672 DONE -> Gerald Meerschaert
45/2672 DONE -> Colby Thicknesse
46/2672 DONE -> Vince Morales
47/2672 DONE -> Ben Johnston
48/2672 DONE -> Wes Schultz
49/2672 DONE -> Jonathan Micallef
50/2672 DONE -> Themba Gorimbo
51/2672 DONE -> Dom Mar Fan
52/2672 DONE -> Kody Steele
53/2672 DONE -> Aljamain Sterling
54/2672 DONE -> Youssef Zalal
55/2672 DONE -> Norma Dumont
56/2672 DONE -> Joselyne Edwards
57/2672 DONE -> Rafa Garcia
58/2672 DONE -> Alexander Hernandez
59/2672 DONE -> Davey Grant
60/2672 DONE -> Adrian Luna Martinetti
61/2672 DONE -> Montel Jackson
62/2672 DONE -> Raoni Barcelos
63/2672 DONE -> Marcus Buchecha
64/2672 DONE -> Ryan Spann
65/2672 DONE -> Rodolfo Vieira
66/2672 DONE -> Eric McConico
67/2672 DONE -> Jackson McVey
68/2672 DONE -> Sedriques Dumas
69/2672 DONE -> Mayra Bueno Silva
70/2672 DONE -> Michelle Montague
71/2672 DONE -> Jafel Filho
72/2672 DONE -> Cody Durden
73/2672 DONE -> Francis Marshall
74/2672 DONE -> Lucas Brennan
75/2672 DONE -> Max Griffin
76/2672 DONE -> Victor Valenzuela
77/2672 DONE -> Talita Alencar
78/2672 DONE -> Julia Polastri
79/2672 DONE -> Gilbert Burns
80/2672 DONE -> Mike Malott
81/2672 DONE -> Kyler Phillips
82/2672 DONE -> Charles Jourdain
83/2672 DONE -> Mandel Nallo
84/2672 DONE -> Jai Herbert
85/2672 DONE -> Jasmine Jasudavicius
86/2672 DONE -> Karine Silva
87/2672 DONE -> Thiago Moises
88/2672 DONE -> Gauge Young
89/2672 DONE -> Dennis Buzukja
90/2672 DONE -> Marcio Barbosa
91/2672 DONE -> Julien Leblanc
92/2672 DONE -> Robert Valentin
93/2672 DONE -> Tanner Boser
94/2672 DONE -> Gokhan Saricam
95/2672 DONE -> Melissa Croden
96/2672 DONE -> Daria Zhelezniakova
97/2672 DONE -> JJ Aldrich
98/2672 DONE -> Jamey-Lyn Horth
99/2672 DONE -> John Castaneda
100/2672 DONE -> Mark Vologdin
101/2672 DONE -> Jamie Siraj
102/2672 DONE -> John Yannis
103/2672 DONE -> Jiri Prochazka
104/2672 DONE -> Carlos Ulberg
105/2672 DONE -> Azamat Murzakanov
106/2672 DONE -> Paulo Costa
107/2672 DONE -> Curtis Blaydes
108/2672 DONE -> Josh Hokit
109/2672 DONE -> Dominick Reyes
110/2672 DONE -> Johnny Walker
111/2672 DONE -> Cub Swanson
112/2672 DONE -> Nate Landwehr
113/2672 DONE -> Patricio Pitbull
114/2672 DONE -> Aaron Pico
115/2672 DONE -> Kevin Holland
116/2672 DONE -> Randy Brown
117/2672 DONE -> Mateusz Gamrot
118/2672 DONE -> Esteban Ribovics
119/2672 DONE -> Tatiana Suarez
120/2672 DONE -> Loopy Godinez
121/2672 DONE -> Chris Padilla
122/2672 DONE -> MarQuel Mederos
123/2672 DONE -> Kelvin Gastelum
124/2672 DONE -> Vicente Luque
125/2672 DONE -> Charles Radtke
126/2672 DONE -> Francisco Prado
127/2672 DONE -> Renato Moicano
128/2672 DONE -> Chris Duncan
129/2672 DONE -> Virna Jandiroba
130/2672 DONE -> Tabatha Ricci
131/2672 DONE -> Abdul Rakhman Yakhyaev
132/2672 DONE -> Brendson Ribeiro
133/2672 DONE -> Ethyn Ewing
134/2672 DONE -> Rafael Estevam
135/2672 DONE -> Tommy McMillen
136/2672 DONE -> Manolo Zecchini
137/2672 DONE -> Jose Delano
138/2672 DONE -> Robert Ruchala
139/2672 DONE -> Guilherme Pat
140/2672 DONE -> Thomas Petersen
141/2672 DONE -> Alessandro Costa
142/2672 DONE -> Stewart Nicoll
143/2672 DONE -> Lando Vannata
144/2672 DONE -> Darrius Flowers
145/2672 DONE -> Alice Pereira
146/2672 DONE -> Hailey Cowan
147/2672 DONE -> Azamat Bekoev
148/2672 DONE -> Tresean Gore
149/2672 DONE -> Dione Barbosa
150/2672 DONE -> Melissa Gatto
151/2672 DONE -> Kai Kamaka III
152/2672 DONE -> Dakota Hope
153/2672 DONE -> Israel Adesanya
154/2672 DONE -> Joe Pyfer
155/2672 DONE -> Alexa Grasso
156/2672 DONE -> Maycee Barber
157/2672 DONE -> Michael Chiesa
158/2672 DONE -> Niko Price
159/2672 DONE -> Julian Erosa
160/2672 DONE -> Lerryan Douglas
161/2672 DONE -> Mansur Abdul-Malik
162/2672 DONE -> Yousri Belgaroui
163/2672 DONE -> Terrance McKinney
164/2672 DONE -> Kyle Nelson
165/2672 DONE -> Ignacio Bahamondes
166/2672 DONE -> Tofiq Musayev
167/2672 DONE -> Chase Hooper
168/2672 DONE -> Lance Gibson Jr.
169/2672 DONE -> Marcin Tybura
170/2672 DONE -> Tyrell Fortune
171/2672 DONE -> Casey O'Neill
172/2672 DONE -> Gabriella Fernandes
173/2672 DONE -> Navajo Stirling
174/2672 DONE -> Bruno Lopes
175/2672 DONE -> Ricky Simon
176/2672 DONE -> Adrian Yanez
177/2672 DONE -> Alexia Thainara
178/2672 DONE -> Bruna Brasil
179/2672 DONE -> Movsar Evloev
180/2672 DONE -> Lerone Murphy
181/2672 DONE -> Luke Riley
182/2672 DONE -> Michael Aswell Jr.
183/2672 DONE -> Michael Page
184/2672 DONE -> Sam Patterson
185/2672 DONE -> Iwo Baraniewski
186/2672 DONE -> Austen Lane
187/2672 DONE -> Roman Dolidze
188/2672 DONE -> Christian Leroy Duncan
189/2672 DONE -> Kurtis Campbell
190/2672 DONE -> Danny Silva
191/2672 DONE -> Mason Jones
192/2672 DONE -> Axel Sola
193/2672 DONE -> Nathaniel Wood
194/2672 DONE -> Losene Keita
195/2672 DONE -> Mario Pinto
196/2672 DONE -> Felipe Franco
197/2672 DONE -> Mantas Kondratavicius
198/2672 DONE -> Antonio Trocoli
199/2672 DONE -> Shem Rock
200/2672 DONE -> Abdul-Kareem Al-Selwady
201/2672 DONE -> Shanelle Dyer
202/2672 DONE -> Ravena Oliveira
203/2672 DONE -> Josh Emmett
204/2672 DONE -> Kevin Vallejos
205/2672 DONE -> Amanda Lemos
206/2672 DONE -> Gillian Robertson
207/2672 DONE -> Andre Fili
208/2672 DONE -> Jose Delgado
209/2672 DONE -> Harry Hardwick
210/2672 DONE -> Ion Cutelaba
211/2672 DONE -> Oumar Sy
212/2672 DONE -> Charles Johnson
213/2672 DONE -> Bruno Silva
214/2672 DONE -> Chris Curtis
215/2672 DONE -> Myktybek Orolbai
216/2672 DONE -> Vitor Petrino
217/2672 DONE -> Steven Asplund
218/2672 DONE -> Elijah Smith
219/2672 DONE -> SuYoung You
220/2672 DONE -> Bolaji Oki
221/2672 DONE -> Manoel Sousa
222/2672 DONE -> Brad Tavares
223/2672 DONE -> Eryk Anders
224/2672 DONE -> Bia Mesquita
225/2672 DONE -> Montse Rendon
226/2672 DONE -> Luan Lacerda
227/2672 DONE -> Hecher Sosa
228/2672 DONE -> Piera Rodriguez
229/2672 DONE -> Sam Hughes
230/2672 DONE -> Max Holloway
231/2672 DONE -> Charles Oliveira
232/2672 DONE -> Caio Borralho
233/2672 DONE -> Reinier de Ridder
234/2672 DONE -> Rob Font
235/2672 DONE -> Raul Rosas Jr.
236/2672 DONE -> Drew Dober
237/2672 DONE -> Michael Johnson
238/2672 DONE -> Gregory Rodrigues
239/2672 DONE -> Brunno Ferreira
240/2672 DONE -> Cody Garbrandt
241/2672 DONE -> Xiao Long
242/2672 DONE -> Donte Johnson
243/2672 DONE -> Cody Brundage
244/2672 DONE -> Ricky Turcios
245/2672 DONE -> Alberto Montes
246/2672 DONE -> Nyamjargal Tumendemberel
247/2672 DONE -> Sumudaerji
248/2672 DONE -> Jesus Aguilar
249/2672 DONE -> Rafael Tobias
250/2672 DONE -> Diyar Nurgozhay
251/2672 DONE -> Luke Fernandez
252/2672 DONE -> Rodolfo Bellato
253/2672 DONE -> Brandon Moreno
254/2672 DONE -> Lone'er Kavanagh
255/2672 DONE -> Marlon Vera
256/2672 DONE -> David Martinez
257/2672 DONE -> Daniel Zellhuber
258/2672 DONE -> Edgar Chairez
259/2672 DONE -> Felipe Bunes
260/2672 DONE -> Imanol Rodriguez
261/2672 DONE -> Kevin Borjas
262/2672 DONE -> Santiago Luna
263/2672 DONE -> Angel Pacheco
264/2672 DONE -> Ryan Gandra
265/2672 DONE -> Jose Daniel Medina
266/2672 DONE -> Ailin Perez
267/2672 DONE -> Macy Chiasson
268/2672 DONE -> Cristian Quinonez
269/2672 DONE -> Kris Moutinho
270/2672 DONE -> Douglas Silva de Andrade
271/2672 DONE -> Javier Reyes
272/2672 DONE -> Regina Tarin
273/2672 DONE -> Ernesta Kareckaite
274/2672 DONE -> Erik Silva
275/2672 DONE -> Damian Pinas
276/2672 DONE -> Anthony Hernandez
277/2672 DONE -> Geoff Neal
278/2672 DONE -> Uros Medic
279/2672 DONE -> Dan Ige
280/2672 DONE -> Melquizael Costa
281/2672 DONE -> Serghei Spivac
282/2672 DONE -> Ante Delija
283/2672 DONE -> Jacobe Smith
284/2672 DONE -> Josiah Harrell
285/2672 DONE -> Zach Reese
286/2672 DONE -> Michel Pereira
287/2672 DONE -> Chidi Njokuani
288/2672 DONE -> Carlos Leal
289/2672 DONE -> Ode Osbourne
290/2672 DONE -> Alibi Idiris
291/2672 DONE -> Alden Coria
292/2672 DONE -> Luis Gurule
293/2672 DONE -> Nora Cornolle
294/2672 DONE -> Ramiz Brahimaj
295/2672 DONE -> Punahele Soriano
296/2672 DONE -> Phil Rowe
297/2672 DONE -> Jean-Paul Lebosnoyani
298/2672 DONE -> Jordan Leavitt
299/2672 DONE -> Yadier del Valle
300/2672 DONE -> Juliana Miller
301/2672 DONE -> Carli Judice
302/2672 DONE -> Mario Bautista
303/2672 DONE -> Vinicius Oliveira
304/2672 DONE -> Amir Albazi
305/2672 DONE -> Kyoji Horiguchi
306/2672 DONE -> Jailton Almeida
307/2672 DONE -> Rizvan Kuniev
308/2672 DONE -> Michal Oleksiejczuk
309/2672 DONE -> Marc-Andre Barriault
310/2672 DONE -> Jean Matsumoto
311/2672 DONE -> Farid Basharat
312/2672 DONE -> Dustin Jacoby
313/2672 DONE -> Julius Walker
314/2672 DONE -> Alex Morono
315/2672 DONE -> Daniil Donchenko
316/2672 DONE -> Nikolay Veretennikov
317/2672 DONE -> Ketlen Souza
318/2672 DONE -> Javid Basharat
319/2672 DONE -> Gianni Vazquez
320/2672 DONE -> Wang Cong
321/2672 DONE -> Eduarda Moura
322/2672 DONE -> Muin Gafurov
323/2672 DONE -> Jakub Wiklacz
324/2672 DONE -> Klaudia Sygula
325/2672 DONE -> Priscila Cachoeira
326/2672 DONE -> Alexander Volkanovski
327/2672 DONE -> Diego Lopes
328/2672 DONE -> Dan Hooker
329/2672 DONE -> Benoit Saint Denis
330/2672 DONE -> Rafael Fiziev
331/2672 DONE -> Mauricio Ruffy
332/2672 DONE -> Tallison Teixeira
333/2672 DONE -> Jamie Mullarkey
334/2672 DONE -> Billy Elekana
335/2672 DONE -> Torrez Finney
336/2672 DONE -> Oban Elliott
337/2672 DONE -> Kaan Ofli
338/2672 DONE -> Yizha
339/2672 DONE -> Sangwook Kim
340/2672 DONE -> Keiichiro Nakamura
341/2672 DONE -> Sebastian Szalay
342/2672 DONE -> Sulangrangbo
343/2672 DONE -> Lawrence Lui
344/2672 DONE -> Justin Gaethje
345/2672 DONE -> Paddy Pimblett
346/2672 DONE -> Sean O'Malley
347/2672 DONE -> Song Yadong
348/2672 DONE -> Derrick Lewis
349/2672 DONE -> Natalia Silva
350/2672 DONE -> Rose Namajunas
351/2672 DONE -> Arnold Allen
352/2672 DONE -> Jean Silva
353/2672 DONE -> Umar Nurmagomedov
354/2672 DONE -> Deiveson Figueiredo
355/2672 DONE -> Andrey Pulyaev
356/2672 DONE -> Nikita Krylov
357/2672 DONE -> Modestas Bukauskas
358/2672 DONE -> Alex Perez
359/2672 DONE -> Denzel Freeman
360/2672 DONE -> Adam Fugitt
361/2672 DONE -> Ty Miller
362/2672 DONE -> Brandon Royval
363/2672 DONE -> Manel Kape
364/2672 DONE -> Giga Chikadze
365/2672 DONE -> Cesar Almeida
366/2672 DONE -> Cezary Oleksiejczuk
367/2672 DONE -> Morgan Charriere
368/2672 DONE -> Kennedy Nzechukwu
369/2672 DONE -> Neil Magny
370/2672 DONE -> Joanderson Brito
371/2672 DONE -> Isaac Thomson
372/2672 DONE -> Sean Sharaf
373/2672 DONE -> Luana Santos
374/2672 DONE -> Allen Frye Jr.
375/2672 DONE -> Tereza Bleda
376/2672 DONE -> Merab Dvalishvili
377/2672 DONE -> Petr Yan
378/2672 DONE -> Alexandre Pantoja
379/2672 DONE -> Henry Cejudo
380/2672 DONE -> Payton Talbott
381/2672 DONE -> Jan Blachowicz
382/2672 DONE -> Bogdan Guskov
383/2672 DONE -> Manuel Torres
384/2672 DONE -> Nazim Sadykhov
385/2672 DONE -> Fares Ziam
386/2672 DONE -> Marvin Vettori
387/2672 DONE -> Edson Barboza
388/2672 DONE -> Jalin Turner
389/2672 DONE -> Ibo Aslan
390/2672 DONE -> Muhammad Naimov
391/2672 DONE -> Mairon Santos
392/2672 DONE -> Arman Tsarukyan
393/2672 DONE -> Belal Muhammad
394/2672 DONE -> Ian Machado Garry
395/2672 DONE -> Volkan Oezdemir
396/2672 DONE -> Alonzo Menifield
397/2672 DONE -> Jack Hermansson
398/2672 DONE -> Tagir Ulanbekov
399/2672 DONE -> Bogdan Grad
400/2672 DONE -> Nicolas Dalby
401/2672 DONE -> Saygid Izagakhmaev
402/2672 DONE -> Asu Almabayev
403/2672 DONE -> Rafael Cerqueira
404/2672 DONE -> Bekzat Almakhan
405/2672 DONE -> Aleksandre Topuria
406/2672 DONE -> Ismail Naurdiev
407/2672 DONE -> Ryan Loder
408/2672 DONE -> Nurullo Aliev
409/2672 DONE -> Marek Bujlo
410/2672 DONE -> Islam Makhachev
411/2672 DONE -> Valentina Shevchenko
412/2672 DONE -> Zhang Weili
413/2672 DONE -> Michael Morales
414/2672 DONE -> Leon Edwards
415/2672 DONE -> Bo Nickal
416/2672 DONE -> Erin Blanchfield
417/2672 DONE -> Tracy Cortez
418/2672 DONE -> Malcolm Wellmaker
419/2672 DONE -> Kyle Daukaus
420/2672 DONE -> Chepe Mariscal
421/2672 DONE -> Angela Hill
422/2672 DONE -> Fatima Kline
423/2672 DONE -> Viacheslav Borshchev
424/2672 DONE -> Matheus Camilo
425/2672 DONE -> Gabriel Bonfim
426/2672 DONE -> Matt Schnell
427/2672 DONE -> Joseph Morales
428/2672 DONE -> Muslim Salikhov
429/2672 DONE -> Ismael Bonfim
430/2672 DONE -> Hyder Amil
431/2672 DONE -> Jamall Emmers
432/2672 DONE -> Jacqueline Cavalcanti
433/2672 DONE -> Max Gimenis
434/2672 DONE -> Tecia Pennington
435/2672 DONE -> Denise Gomes
436/2672 DONE -> Miles Johns
437/2672 DONE -> Daniel Marcos
438/2672 DONE -> Steve Garcia
439/2672 DONE -> David Onama
440/2672 DONE -> Jeremiah Wells
441/2672 DONE -> Isaac Dulgarian
442/2672 DONE -> Daniel Frunza
443/2672 DONE -> Allan Nascimento
444/2672 DONE -> Timmy Cuamba
445/2672 DONE -> ChangHo Lee
446/2672 DONE -> Ketlen Vieira
447/2672 DONE -> Alice Ardelean
448/2672 DONE -> Montserrat Conejo Ruiz
449/2672 DONE -> Seokhyeon Ko
450/2672 DONE -> Ariane Carnelossi
451/2672 DONE -> Tom Aspinall
452/2672 DONE -> Ciryl Gane
453/2672 DONE -> Mackenzie Dern
454/2672 DONE -> Aleksandar Rakic
455/2672 DONE -> Nasrat Haqparast
456/2672 DONE -> Ikram Aliskerov
457/2672 DONE -> JunYong Park
458/2672 DONE -> Ludovit Klein
459/2672 DONE -> Valter Walker
460/2672 DONE -> Hamdy Abdelwahab
461/2672 DONE -> Chris Barnett
462/2672 DONE -> Azat Maksum
463/2672 DONE -> Mitch Raposo
464/2672 DONE -> Jaqueline Amorim
465/2672 DONE -> Mizuki
466/2672 DONE -> Brendan Allen
467/2672 DONE -> Aiemann Zahabi
468/2672 DONE -> Manon Fiorot
469/2672 DONE -> Matt Frevola
470/2672 DONE -> Kyle Prepolec
471/2672 DONE -> Cody Gibson
472/2672 DONE -> Aoriqileng
473/2672 DONE -> HyunSung Park
474/2672 DONE -> Danny Barlow
475/2672 DONE -> Stephanie Luciano
476/2672 DONE -> Tainara Lisboa
477/2672 DONE -> Jhonata Diniz
478/2672 DONE -> Ricardo Ramos
479/2672 DONE -> Lucas Almeida
480/2672 DONE -> Irina Alekseeva
481/2672 DONE -> Lucas Rocha
482/2672 DONE -> Karolina Kowalkiewicz
483/2672 DONE -> Saimon Oliveira
484/2672 DONE -> Magomed Ankalaev
485/2672 DONE -> Alex Pereira
486/2672 DONE -> Cory Sandhagen
487/2672 DONE -> Khalil Rountree Jr.
488/2672 DONE -> Abus Magomedov
489/2672 DONE -> Tre'ston Vines
490/2672 DONE -> Daniel Santos
491/2672 DONE -> JooSang Yoo
492/2672 DONE -> Patchy Mix
493/2672 DONE -> Edmen Shahbazyan
494/2672 DONE -> Andre Muniz
495/2672 DONE -> Yana Santos
496/2672 DONE -> Chris Gutierrez
497/2672 DONE -> Austin Vanderford
498/2672 DONE -> Veronica Hardy
499/2672 DONE -> Brogan Walker
500/2672 DONE -> Jimmy Crute
501/2672 DONE -> Ivan Erslan
502/2672 DONE -> Jack Jenkins
503/2672 DONE -> Ramon Taveras
504/2672 DONE -> Jake Matthews
505/2672 DONE -> Tom Nolan
506/2672 DONE -> Charlie Campbell
507/2672 DONE -> Andre Petroski
508/2672 DONE -> Rolando Bedoya
509/2672 DONE -> Josias Musasa
510/2672 DONE -> Luana Carolina
511/2672 DONE -> Elisha Ellison
512/2672 DONE -> Loma Lookboonmee
513/2672 DONE -> Dustin Stoltzfus
514/2672 DONE -> Diego Ferreira
515/2672 DONE -> Quang Le
516/2672 DONE -> Dusko Todorovic
517/2672 DONE -> Claudio Puelles
518/2672 DONE -> Joaquim Silva
519/2672 DONE -> Rodrigo Sezinando
520/2672 DONE -> Nassourdine Imavov
521/2672 DONE -> Paul Craig
522/2672 DONE -> Rhys McKee
523/2672 DONE -> Kaue Fernandes
524/2672 DONE -> Trey Waters
525/2672 DONE -> Andreas Gustafsson
526/2672 DONE -> Rinat Fakhretdinov
527/2672 DONE -> Shauna Bannon
528/2672 DONE -> Zhang Mingyang
529/2672 DONE -> Brian Ortega
530/2672 DONE -> Sergei Pavlovich
531/2672 DONE -> Taiyilake Nueraji
532/2672 DONE -> Kiefer Crosbie
533/2672 DONE -> Maheshate
534/2672 DONE -> Rongzhu
535/2672 DONE -> Austin Hubbard
536/2672 DONE -> Westin Wilson
537/2672 DONE -> Uran Satybaldiev
538/2672 DONE -> Shi Ming
539/2672 DONE -> Terrance Saeteurn
540/2672 DONE -> Dricus Du Plessis
541/2672 DONE -> Jared Cannonier
542/2672 DONE -> Kai Asakura
543/2672 DONE -> Eric Nolan
544/2672 DONE -> Jessica Andrade
545/2672 DONE -> Drakkar Klose
546/2672 DONE -> Iasmin Lucindo
547/2672 DONE -> Christian Rodriguez
548/2672 DONE -> Toshiomi Kazama
549/2672 DONE -> Gilbert Urbina
550/2672 DONE -> Julija Stoliarenko
551/2672 DONE -> Elves Brener
552/2672 DONE -> Karol Rosa
553/2672 DONE -> Elizeu Zaleski dos Santos
554/2672 DONE -> Rinya Nakamura
555/2672 DONE -> Nathan Fletcher
556/2672 DONE -> Nick Klein
557/2672 DONE -> Austin Bashi
558/2672 DONE -> Robert Whittaker
559/2672 DONE -> Marcus McGhee
560/2672 DONE -> Shara Magomedov
561/2672 DONE -> Bryce Mitchell
562/2672 DONE -> Said Nurmagomedov
563/2672 DONE -> Da'Mon Blackshear
564/2672 DONE -> Amanda Ribas
565/2672 DONE -> Mohammad Yahya
566/2672 DONE -> Steven Nguyen
567/2672 DONE -> Martin Buday
568/2672 DONE -> Dustin Poirier
569/2672 DONE -> Daniel Rodriguez
570/2672 DONE -> Islam Dulatov
571/2672 DONE -> Marcin Prachnio
572/2672 DONE -> Lukasz Brzeski
573/2672 DONE -> Nicolle Caliari
574/2672 DONE -> Stephen Thompson
575/2672 DONE -> Calvin Kattar
576/2672 DONE -> Tuco Tokkos
577/2672 DONE -> Lauren Murphy
578/2672 DONE -> Mitch Ramirez
579/2672 DONE -> Mike Davis
580/2672 DONE -> Melissa Martinez
581/2672 DONE -> Ilia Topuria
582/2672 DONE -> Kai Kara-France
583/2672 DONE -> Felipe Lima
584/2672 DONE -> Viviane Araujo
585/2672 DONE -> Alvin Hines
586/2672 DONE -> Jamahal Hill
587/2672 DONE -> Nikolas Motta
588/2672 DONE -> Melissa Mullins
589/2672 DONE -> Mohammed Usman
590/2672 DONE -> Kamaru Usman
591/2672 DONE -> Miranda Maverick
592/2672 DONE -> Court McGee
593/2672 DONE -> Cameron Smotherman
594/2672 DONE -> Ange Loosa
595/2672 DONE -> Vanessa Demopoulos
596/2672 DONE -> Julianna Pena
597/2672 DONE -> Kayla Harrison
598/2672 DONE -> Khaos Williams
599/2672 DONE -> Ariane da Silva
600/2672 DONE -> Jeka Saragih
601/2672 DONE -> Yanal Ashmouz
602/2672 DONE -> Mark Choinski
603/2672 DONE -> Billy Ray Goff
604/2672 DONE -> Kurt Holobaugh
605/2672 DONE -> Rayanne dos Santos
606/2672 DONE -> Sodiq Yusuff
607/2672 DONE -> Nursulton Ruziboev
608/2672 DONE -> Gabe Green
609/2672 DONE -> Connor Matthews
610/2672 DONE -> Elise Reed
611/2672 DONE -> Carlos Hernandez
612/2672 DONE -> Luana Pinheiro
613/2672 DONE -> Jose Aldo
614/2672 DONE -> Bruno Silva
615/2672 DONE -> JeongYeong Lee
616/2672 DONE -> Brad Katona
617/2672 DONE -> Santiago Ponzinibbio
618/2672 DONE -> Serhiy Sidey
619/2672 DONE -> Miesha Tate
620/2672 DONE -> Marina Rodriguez
621/2672 DONE -> Gaston Bolanos
622/2672 DONE -> Don'Tale Mayes
623/2672 DONE -> Ivana Petrovic
624/2672 DONE -> Anthony Smith
625/2672 DONE -> Jimmy Flick
626/2672 DONE -> Evan Elder
627/2672 DONE -> Alatengheili
628/2672 DONE -> Cameron Saaiman
629/2672 DONE -> Polyana Viana
630/2672 DONE -> Roberto Romero
631/2672 DONE -> Chelsea Chandler
632/2672 DONE -> Michael Chandler
633/2672 DONE -> Yair Rodriguez
634/2672 DONE -> Sean Woodson
635/2672 DONE -> Yan Xiaonan
636/2672 DONE -> Darren Elkins

In [17]:
fighters_df.to_csv('fighters.csv',index=False)

In [18]:
fighters_df.head(2)

,url,name,nickname,record,wins,losses,draws,Height,Weight,Reach,STANCE,DOB,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.
0,http://ufcstats.com/fighter-details/767755fd74...,Khamzat Chimaev,Borz,15-1-0,15,1,0.0,"6' 2""",185 lbs.,"75""",Orthodox,"May 01, 1994",4.01,54%,2.98,52%,5.32,58%,87%,1.4
1,http://ufcstats.com/fighter-details/0d8011111b...,Sean Strickland,,31-7-0,31,7,0.0,"6' 1""",185 lbs.,"76""",Orthodox,"Feb 27, 1991",5.98,42%,4.53,60%,0.66,62%,68%,0.1

In [3]:
#giving id 
import pandas as pd
fighters_df = pd.read_csv('fighters.csv')
fighters_df['ID'] = [i for i in range(fighters_df.shape[0],0,-1)]
fighters_df.head(3)
fighters_df.to_csv('fighters_correct_with_id.csv',index=False)

In [2]:
fighters_df.tail(4)

,url,name,nickname,record,wins,losses,draws,Height,Weight,Reach,...,DOB,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.,ID
2668,http://ufcstats.com/fighter-details/505934897b...,Thaddeus Luster,NaN,0-1-0,0,1,0.0,"6' 3""",210 lbs.,--,...,--,0.0,0%,0.0,0%,0.0,0%,0%,0.0,4
2669,http://ufcstats.com/fighter-details/49590e0508...,David Levicki,NaN,1-3-0,1,3,0.0,"6' 5""",275 lbs.,--,...,--,0.0,0%,0.0,0%,0.0,0%,0%,0.0,3
2670,http://ufcstats.com/fighter-details/ea0ad15545...,Ray Wizard,NaN,0-1-0,0,1,0.0,--,--,--,...,--,0.0,0%,0.0,0%,0.0,0%,0%,0.0,2
2671,http://ufcstats.com/fighter-details/a683f9ddb7...,Sean Daugherty,NaN,0-2-0,0,2,0.0,"6' 0""",175 lbs.,--,...,"Dec 04, 1975",0.0,0%,0.0,0%,0.0,0%,0%,0.0,1