In [17]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

print('ok')

ok

## SCRAPING

In [ ]:
#εδώ είναι το λινκ που περιέχει όλα τα events 
URL = "http://ufcstats.com/statistics/events/completed?page=all"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(URL, headers=headers)

In [11]:
response.status_code

200

In [12]:
soup = BeautifulSoup(response.text, "html.parser")

In [13]:
rows = soup.select("tr.b-statistics__table-row")

len(rows)

775

In [14]:
events = []

for row in rows:

    link = row.find("a")

    if link:

        event_name = link.text.strip()

        event_url = link["href"]

        cells = row.find_all("td")

        date = cells[0].text.strip()

        location = cells[1].text.strip()

        events.append({
            "event_name": event_name,
            "event_url": event_url,
            "date": date,
            "location": location
        })

In [15]:
events

[{'event_name': 'UFC 328: Chimaev vs. Strickland',
  'event_url': 'http://ufcstats.com/event-details/9eedac48b497de5a',
  'date': 'UFC 328: Chimaev vs. Strickland\n                        \n\n                          May 09, 2026',
  'location': 'Newark, New Jersey, USA'},
 {'event_name': 'UFC Fight Night: Della Maddalena vs. Prates',
  'event_url': 'http://ufcstats.com/event-details/872b018076f831b0',
  'date': 'UFC Fight Night: Della Maddalena vs. Prates\n                        \n\n                          May 02, 2026',
  'location': 'Perth, Western Australia, Australia'},
 {'event_name': 'UFC Fight Night: Sterling vs. Zalal',
  'event_url': 'http://ufcstats.com/event-details/e60d773a0a42048a',
  'date': 'UFC Fight Night: Sterling vs. Zalal\n                        \n\n                          April 25, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Burns vs. Malott',
  'event_url': 'http://ufcstats.com/event-details/c3ac8d0da7b05772',
  'date': 'UFC Fight Night: Burns vs. Malott\n                        \n\n                          April 18, 2026',
  'location': 'Winnipeg, Manitoba, Canada'},
 {'event_name': 'UFC 327: Prochazka vs. Ulberg',
  'event_url': 'http://ufcstats.com/event-details/f3eb664db7fb1df3',
  'date': 'UFC 327: Prochazka vs. Ulberg\n                        \n\n                          April 11, 2026',
  'location': 'Miami, Florida, USA'},
 {'event_name': 'UFC Fight Night: Moicano vs. Duncan',
  'event_url': 'http://ufcstats.com/event-details/9a70f67ad2187fa3',
  'date': 'UFC Fight Night: Moicano vs. Duncan\n                        \n\n                          April 04, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Adesanya vs. Pyfer',
  'event_url': 'http://ufcstats.com/event-details/5c38639f860a5542',
  'date': 'UFC Fight Night: Adesanya vs. Pyfer\n                        \n\n                          March 28, 2026',
  'location': 'Seattle, Washington, USA'},
 {'event_name': 'UFC Fight Night: Evloev vs. Murphy',
  'event_url': 'http://ufcstats.com/event-details/69108cb8b32efe04',
  'date': 'UFC Fight Night: Evloev vs. Murphy\n                        \n\n                          March 21, 2026',
  'location': 'London, England, United Kingdom'},
 {'event_name': 'UFC Fight Night: Emmett vs. Vallejos',
  'event_url': 'http://ufcstats.com/event-details/babc6b5745335f18',
  'date': 'UFC Fight Night: Emmett vs. Vallejos\n                        \n\n                          March 14, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 326: Holloway vs. Oliveira 2',
  'event_url': 'http://ufcstats.com/event-details/15ec018d144710db',
  'date': 'UFC 326: Holloway vs. Oliveira 2\n                        \n\n                          March 07, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Moreno vs. Kavanagh',
  'event_url': 'http://ufcstats.com/event-details/0cfbbfa0ba6d9855',
  'date': 'UFC Fight Night: Moreno vs. Kavanagh\n                        \n\n                          February 28, 2026',
  'location': 'Mexico City, Distrito Federal, Mexico'},
 {'event_name': 'UFC Fight Night: Strickland vs. Hernandez',
  'event_url': 'http://ufcstats.com/event-details/79ab17db3b40831a',
  'date': 'UFC Fight Night: Strickland vs. Hernandez\n                        \n\n                          February 21, 2026',
  'location': 'Houston, Texas, USA'},
 {'event_name': 'UFC Fight Night: Bautista vs. Oliveira',
  'event_url': 'http://ufcstats.com/event-details/c337c3c85b1871e0',
  'date': 'UFC Fight Night: Bautista vs. Oliveira\n                        \n\n                          February 07, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 325: Volkanovski vs. Lopes 2',
  'event_url': 'http://ufcstats.com/event-details/30ad2050273d016a',
  'date': 'UFC 325: Volkanovski vs. Lopes 2\n                        \n\n                          January 31, 2026',
  'location': 'Sydney, New South Wales, Australia'},
 {'event_name': 'UFC 324: Gaethje vs. Pimblett',
  'event_url': 'http://ufcstats.com/event-details/00e11b5c8b7bfeeb',
  'date': 'UFC 324: Gaethje vs. Pimblett\n                        \n\n                          January 24, 2026',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Royval vs. Kape',
  'event_url': 'http://ufcstats.com/event-details/bc0f994de0521926',
  'date': 'UFC Fight Night: Royval vs. Kape\n                        \n\n                          December 13, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 323: Dvalishvili vs. Yan 2',
  'event_url': 'http://ufcstats.com/event-details/bd92cf5da5413d2a',
  'date': 'UFC 323: Dvalishvili vs. Yan 2\n                        \n\n                          December 06, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Tsarukyan vs. Hooker',
  'event_url': 'http://ufcstats.com/event-details/92c96df8bdab5fea',
  'date': 'UFC Fight Night: Tsarukyan vs. Hooker\n                        \n\n                          November 22, 2025',
  'location': 'Doha, Qatar'},
 {'event_name': 'UFC 322: Della Maddalena vs. Makhachev',
  'event_url': 'http://ufcstats.com/event-details/8db1b36dde268ef6',
  'date': 'UFC 322: Della Maddalena vs. Makhachev\n                        \n\n                          November 15, 2025',
  'location': 'New York City, New York, USA'},
 {'event_name': 'UFC Fight Night: Bonfim vs. Brown',
  'event_url': 'http://ufcstats.com/event-details/6436029b50a9c255',
  'date': 'UFC Fight Night: Bonfim vs. Brown\n                        \n\n                          November 08, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Garcia vs. Onama',
  'event_url': 'http://ufcstats.com/event-details/0e2c2daf11b5d8f2',
  'date': 'UFC Fight Night: Garcia vs. Onama\n                        \n\n                          November 01, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 321: Aspinall vs. Gane',
  'event_url': 'http://ufcstats.com/event-details/7956f026e2672c47',
  'date': 'UFC 321: Aspinall vs. Gane\n                        \n\n                          October 25, 2025',
  'location': 'Abu Dhabi, Abu Dhabi, United Arab Emirates'},
 {'event_name': 'UFC Fight Night: De Ridder vs. Allen',
  'event_url': 'http://ufcstats.com/event-details/38e5d9dcb0fddc42',
  'date': 'UFC Fight Night: De Ridder vs. Allen\n                        \n\n                          October 18, 2025',
  'location': 'Vancouver, British Columbia, Canada'},
 {'event_name': 'UFC Fight Night: Oliveira vs. Gamrot',
  'event_url': 'http://ufcstats.com/event-details/9336e86cfd4ceaa1',
  'date': 'UFC Fight Night: Oliveira vs. Gamrot\n                        \n\n                          October 11, 2025',
  'location': 'Rio de Janeiro, Rio de Janeiro, Brazil'},
 {'event_name': 'UFC 320: Ankalaev vs. Pereira 2',
  'event_url': 'http://ufcstats.com/event-details/8944a0f9b2f0ce6d',
  'date': 'UFC 320: Ankalaev vs. Pereira 2\n                        \n\n                          October 04, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Ulberg vs. Reyes',
  'event_url': 'http://ufcstats.com/event-details/ed220e87bef0cc64',
  'date': 'UFC Fight Night: Ulberg vs. Reyes\n                        \n\n                          September 27, 2025',
  'location': 'Perth, Western Australia, Australia'},
 {'event_name': 'UFC Fight Night: Lopes vs. Silva',
  'event_url': 'http://ufcstats.com/event-details/5efaaf313b652dd7',
  'date': 'UFC Fight Night: Lopes vs. Silva\n                        \n\n                          September 13, 2025',
  'location': 'San Antonio, Texas, USA'},
 {'event_name': 'UFC Fight Night: Imavov vs. Borralho',
  'event_url': 'http://ufcstats.com/event-details/6e380a4d73ab4f0e',
  'date': 'UFC Fight Night: Imavov vs. Borralho\n                        \n\n                          September 06, 2025',
  'location': 'Paris, Ile-de-France, France'},
 {'event_name': 'UFC Fight Night: Walker vs. Zhang',
  'event_url': 'http://ufcstats.com/event-details/754968e325d6f60d',
  'date': 'UFC Fight Night: Walker vs. Zhang\n                        \n\n                          August 23, 2025',
  'location': 'Shanghai, Hebei, China'},
 {'event_name': 'UFC - Road to UFC 4.6',
  'event_url': 'http://ufcstats.com/event-details/8fbcd82bf7f352bf',
  'date': 'UFC - Road to UFC 4.6\n                        \n\n                          August 22, 2025',
  'location': 'Shanghai, Hebei, China'},
 {'event_name': 'UFC 319: Du Plessis vs. Chimaev',
  'event_url': 'http://ufcstats.com/event-details/421ccfc6ddb17958',
  'date': 'UFC 319: Du Plessis vs. Chimaev\n                        \n\n                          August 16, 2025',
  'location': 'Chicago, Illinois, USA'},
 {'event_name': 'UFC Fight Night: Dolidze vs. Hernandez',
  'event_url': 'http://ufcstats.com/event-details/6cd3dfc54f01287f',
  'date': 'UFC Fight Night: Dolidze vs. Hernandez\n                        \n\n                          August 09, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Taira vs. Park',
  'event_url': 'http://ufcstats.com/event-details/f2c934689243fe4e',
  'date': 'UFC Fight Night: Taira vs. Park\n                        \n\n                          August 02, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Whittaker vs. De Ridder',
  'event_url': 'http://ufcstats.com/event-details/28d8638ea0a71908',
  'date': 'UFC Fight Night: Whittaker vs. De Ridder\n                        \n\n                          July 26, 2025',
  'location': 'Abu Dhabi, Abu Dhabi, United Arab Emirates'},
 {'event_name': 'UFC 318: Holloway vs. Poirier 3',
  'event_url': 'http://ufcstats.com/event-details/b8e2f10efb6eca85',
  'date': 'UFC 318: Holloway vs. Poirier 3\n                        \n\n                          July 19, 2025',
  'location': 'New Orleans, Louisiana, USA'},
 {'event_name': 'UFC Fight Night: Lewis vs. Teixeira',
  'event_url': 'http://ufcstats.com/event-details/7b03d9df5910917d',
  'date': 'UFC Fight Night: Lewis vs. Teixeira\n                        \n\n                          July 12, 2025',
  'location': 'Nashville, Tennessee, USA'},
 {'event_name': 'UFC 317: Topuria vs. Oliveira',
  'event_url': 'http://ufcstats.com/event-details/66766984842c13dc',
  'date': 'UFC 317: Topuria vs. Oliveira\n                        \n\n                          June 28, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Hill vs. Rountree Jr.',
  'event_url': 'http://ufcstats.com/event-details/400c7b43c86d27d3',
  'date': 'UFC Fight Night: Hill vs. Rountree Jr.\n                        \n\n                          June 21, 2025',
  'location': 'Baku, Azerbaijan'},
 {'event_name': 'UFC Fight Night: Usman vs. Buckley',
  'event_url': 'http://ufcstats.com/event-details/de277a4abcfeea46',
  'date': 'UFC Fight Night: Usman vs. Buckley\n                        \n\n                          June 14, 2025',
  'location': 'Atlanta, Georgia, USA'},
 {'event_name': "UFC 316: Dvalishvili vs. O'Malley 2",
  'event_url': 'http://ufcstats.com/event-details/18c49685296c60e6',
  'date': "UFC 316: Dvalishvili vs. O'Malley 2\n                        \n\n                          June 07, 2025",
  'location': 'Newark, New Jersey, USA'},
 {'event_name': 'UFC Fight Night: Blanchfield vs. Barber',
  'event_url': 'http://ufcstats.com/event-details/2a898bf9fb7710b3',
  'date': 'UFC Fight Night: Blanchfield vs. Barber\n                        \n\n                          May 31, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Burns vs. Morales',
  'event_url': 'http://ufcstats.com/event-details/8ad022dd81224f61',
  'date': 'UFC Fight Night: Burns vs. Morales\n                        \n\n                          May 17, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 315: Muhammad vs. Della Maddalena',
  'event_url': 'http://ufcstats.com/event-details/118463dd8db16e7f',
  'date': 'UFC 315: Muhammad vs. Della Maddalena\n                        \n\n                          May 10, 2025',
  'location': 'Montreal, Quebec, Canada'},
 {'event_name': 'UFC Fight Night: Sandhagen vs. Figueiredo',
  'event_url': 'http://ufcstats.com/event-details/de20ffb3fc2e7629',
  'date': 'UFC Fight Night: Sandhagen vs. Figueiredo\n                        \n\n                          May 03, 2025',
  'location': 'Des Moines, Iowa, USA'},
 {'event_name': 'UFC Fight Night: Machado Garry vs. Prates',
  'event_url': 'http://ufcstats.com/event-details/b2e3aca4cd363477',
  'date': 'UFC Fight Night: Machado Garry vs. Prates\n                        \n\n                          April 26, 2025',
  'location': 'Kansas City, Missouri, USA'},
 {'event_name': 'UFC 314: Volkanovski vs. Lopes',
  'event_url': 'http://ufcstats.com/event-details/22f4b6cb6b1bd7fd',
  'date': 'UFC 314: Volkanovski vs. Lopes\n                        \n\n                          April 12, 2025',
  'location': 'Miami, Florida, USA'},
 {'event_name': 'UFC Fight Night: Emmett vs. Murphy',
  'event_url': 'http://ufcstats.com/event-details/86b30a86664cb6e4',
  'date': 'UFC Fight Night: Emmett vs. Murphy\n                        \n\n                          April 05, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Moreno vs. Erceg',
  'event_url': 'http://ufcstats.com/event-details/0f7210aa8d61af8d',
  'date': 'UFC Fight Night: Moreno vs. Erceg\n                        \n\n                          March 29, 2025',
  'location': 'Mexico City, Distrito Federal, Mexico'},
 {'event_name': 'UFC Fight Night: Edwards vs. Brady',
  'event_url': 'http://ufcstats.com/event-details/cc2ad11b1f9d818b',
  'date': 'UFC Fight Night: Edwards vs. Brady\n                        \n\n                          March 22, 2025',
  'location': 'London, England, United Kingdom'},
 {'event_name': 'UFC Fight Night: Vettori vs. Dolidze 2',
  'event_url': 'http://ufcstats.com/event-details/39f62b833e4cf126',
  'date': 'UFC Fight Night: Vettori vs. Dolidze 2\n                        \n\n                          March 15, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 313: Pereira vs. Ankalaev',
  'event_url': 'http://ufcstats.com/event-details/ca936c67687789e9',
  'date': 'UFC 313: Pereira vs. Ankalaev\n                        \n\n                          March 08, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Kape vs. Almabayev',
  'event_url': 'http://ufcstats.com/event-details/9766ed20b68c7c33',
  'date': 'UFC Fight Night: Kape vs. Almabayev\n                        \n\n                          March 01, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Cejudo vs. Song',
  'event_url': 'http://ufcstats.com/event-details/c50ea21fe9ef478d',
  'date': 'UFC Fight Night: Cejudo vs. Song\n                        \n\n                          February 22, 2025',
  'location': 'Seattle, Washington, USA'},
 {'event_name': 'UFC Fight Night: Cannonier vs. Rodrigues',
  'event_url': 'http://ufcstats.com/event-details/ce7871949b0ed2bf',
  'date': 'UFC Fight Night: Cannonier vs. Rodrigues\n                        \n\n                          February 15, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 312: Du Plessis vs. Strickland 2',
  'event_url': 'http://ufcstats.com/event-details/e6015889f50075d2',
  'date': 'UFC 312: Du Plessis vs. Strickland 2\n                        \n\n                          February 08, 2025',
  'location': 'Sydney, New South Wales, Australia'},
 {'event_name': 'UFC Fight Night: Adesanya vs. Imavov',
  'event_url': 'http://ufcstats.com/event-details/80dbeb1dd5b53e64',
  'date': 'UFC Fight Night: Adesanya vs. Imavov\n                        \n\n                          February 01, 2025',
  'location': 'Riyadh, Riyadh, Saudi Arabia'},
 {'event_name': 'UFC 311: Makhachev vs. Moicano',
  'event_url': 'http://ufcstats.com/event-details/39f68882def7a507',
  'date': 'UFC 311: Makhachev vs. Moicano\n                        \n\n                          January 18, 2025',
  'location': 'Inglewood, California, USA'},
 {'event_name': 'UFC Fight Night: Dern vs. Ribas 2',
  'event_url': 'http://ufcstats.com/event-details/81ddc98fceb30086',
  'date': 'UFC Fight Night: Dern vs. Ribas 2\n                        \n\n                          January 11, 2025',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Covington vs. Buckley',
  'event_url': 'http://ufcstats.com/event-details/72c9c2eadfc3277e',
  'date': 'UFC Fight Night: Covington vs. Buckley\n                        \n\n                          December 14, 2024',
  'location': 'Tampa, Florida, USA'},
 {'event_name': 'UFC 310: Pantoja vs. Asakura',
  'event_url': 'http://ufcstats.com/event-details/ad23903ef3af7406',
  'date': 'UFC 310: Pantoja vs. Asakura\n                        \n\n                          December 07, 2024',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Yan vs. Figueiredo',
  'event_url': 'http://ufcstats.com/event-details/e955046551f8c7dd',
  'date': 'UFC Fight Night: Yan vs. Figueiredo\n                        \n\n                          November 23, 2024',
  'location': 'Macau, China'},
 {'event_name': 'UFC 309: Jones vs. Miocic',
  'event_url': 'http://ufcstats.com/event-details/daff32bc96d1eabf',
  'date': 'UFC 309: Jones vs. Miocic\n                        \n\n                          November 16, 2024',
  'location': 'New York City, New York, USA'},
 {'event_name': 'UFC Fight Night: Magny vs. Prates',
  'event_url': 'http://ufcstats.com/event-details/585f9ffdb0cd0466',
  'date': 'UFC Fight Night: Magny vs. Prates\n                        \n\n                          November 09, 2024',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Moreno vs. Albazi',
  'event_url': 'http://ufcstats.com/event-details/3ab0df1ddd5f1dc2',
  'date': 'UFC Fight Night: Moreno vs. Albazi\n                        \n\n                          November 02, 2024',
  'location': 'Edmonton, Alberta, Canada'},
 {'event_name': 'UFC 308: Topuria vs. Holloway',
  'event_url': 'http://ufcstats.com/event-details/221b2a3070c7ce3e',
  'date': 'UFC 308: Topuria vs. Holloway\n                        \n\n                          October 26, 2024',
  'location': 'Abu Dhabi, Abu Dhabi, United Arab Emirates'},
 {'event_name': 'UFC Fight Night: Hernandez vs. Pereira',
  'event_url': 'http://ufcstats.com/event-details/6a0047ac8c99fece',
  'date': 'UFC Fight Night: Hernandez vs. Pereira\n                        \n\n                          October 19, 2024',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC Fight Night: Royval vs. Taira',
  'event_url': 'http://ufcstats.com/event-details/5bdcbd8dd681a257',
  'date': 'UFC Fight Night: Royval vs. Taira\n                        \n\n                          October 12, 2024',
  'location': 'Las Vegas, Nevada, USA'},
 {'event_name': 'UFC 307: Pereira vs. Rountree Jr.',
  'event_url': 'http://ufcstats.com/event-details/eee8efec7b951d84',
  'date': 'UFC 307: Pereira vs. Rountree Jr.\n                        \n\n                          October 05, 2024',
  'location': 'Salt Lake City, Utah, USA'},
 {'event_name': 'UFC Fight Night: Moicano vs. Saint Denis',
  'event_url': 'http://ufcstats.com/event-details/079488710f012779',
  'date': 'UFC Fight Night: Moicano vs. Saint Denis\n                        \n\n                          September 28, 2024',
  'location': 'Paris, Ile-de-France, France'},
 {'event_name': 'UFC 306: Riyadh Season Noche UFC',
  'event_url': 'http://ufcstats.com/event-details/0c01568b1ac77bff',
  'date': 'UFC 306: Riyadh Season Noche UFC\n                        \n\n                          September 14, 2024',

In [16]:
len(events)

773

In [19]:
df_events = pd.DataFrame(events)

## CLEANING

In [24]:
df_events.head()

,event_name,event_url,date,location
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/event-details/9eedac48b497...,UFC 328: Chimaev vs. Strickland\n ...,"Newark, New Jersey, USA"
1,UFC Fight Night: Della Maddalena vs. Prates,http://ufcstats.com/event-details/872b018076f8...,UFC Fight Night: Della Maddalena vs. Prates\n ...,"Perth, Western Australia, Australia"
2,UFC Fight Night: Sterling vs. Zalal,http://ufcstats.com/event-details/e60d773a0a42...,UFC Fight Night: Sterling vs. Zalal\n ...,"Las Vegas, Nevada, USA"
3,UFC Fight Night: Burns vs. Malott,http://ufcstats.com/event-details/c3ac8d0da7b0...,UFC Fight Night: Burns vs. Malott\n ...,"Winnipeg, Manitoba, Canada"
4,UFC 327: Prochazka vs. Ulberg,http://ufcstats.com/event-details/f3eb664db7fb...,UFC 327: Prochazka vs. Ulberg\n ...,"Miami, Florida, USA"

In [ ]:
df_events['date'][100] ## βλέπω ότι δεν τα πέρνει σωστά επομένως πρέπει να τα περιορίσω

'UFC 296: Edwards vs. Covington\n                        \n\n                          December 16, 2023'

In [ ]:
## τεστάρω να δω τι θα κόψω
## θα πάρω τα τελευταία 18 στοιχία καθώς ο μεγαλύτερος μήνας έχει 9 στοιχία + 9 πάμε μαξ 18 

for i in range(df_events.shape[0]):
    print(str(df_events['date'][i])[-18:].strip())
    if i > 10 :
        break

May 09, 2026
May 02, 2026
April 25, 2026
April 18, 2026
April 11, 2026
April 04, 2026
March 28, 2026
March 21, 2026
March 14, 2026
March 07, 2026
February 28, 2026
February 21, 2026

In [46]:
## αλλάζω το date

df_events['date'] = df_events['date'].astype(str).str[-18:].str.strip()

In [49]:
df_events.head(5)

,event_name,event_url,date,location
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/event-details/9eedac48b497...,"May 09, 2026","Newark, New Jersey, USA"
1,UFC Fight Night: Della Maddalena vs. Prates,http://ufcstats.com/event-details/872b018076f8...,"May 02, 2026","Perth, Western Australia, Australia"
2,UFC Fight Night: Sterling vs. Zalal,http://ufcstats.com/event-details/e60d773a0a42...,"April 25, 2026","Las Vegas, Nevada, USA"
3,UFC Fight Night: Burns vs. Malott,http://ufcstats.com/event-details/c3ac8d0da7b0...,"April 18, 2026","Winnipeg, Manitoba, Canada"
4,UFC 327: Prochazka vs. Ulberg,http://ufcstats.com/event-details/f3eb664db7fb...,"April 11, 2026","Miami, Florida, USA"

In [50]:
## θα πάω τωρα να σπάσω το date σε μήνα - μέρα - έτος  το location σε πόλη και χώρα και το event_name σε fight_night ή κανονικό ή άλλο

In [56]:
## πρώτο !

month = []
day = []
year = []
for i in range(df_events.shape[0]):
    broken = df_events['date'][i].split(' ')
    month.append(broken[0])
    day.append(str(broken[1]).replace(',',''))
    year.append(broken[2])

In [57]:
df_events['day'] = day
df_events['month'] = month
df_events['year'] = year

In [59]:
df_events.drop(columns=['date'],inplace=True)

In [71]:
##2o !!
## κάποιες τοποθεσίες δεν έχουν  ρεγιον 
city=[]
region = []
country = []

for i in range(df_events.shape[0]):
    broken = df_events['location'][i].split(',')
    if len(broken) == 3:
        city.append(broken[0])
        region.append(broken[1])
        country.append(broken[2])


    if len(broken) <3 :
        city.append(broken[0])
        country.append(broken[1])
        region.append('unknown')

In [73]:
df_events['city'] = city
df_events['region'] = region
df_events['country'] = country

In [75]:
df_events.drop(columns=['location'],inplace=True)

In [76]:
df_events.head(2)

,event_name,event_url,day,month,year,city,region,country
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/event-details/9eedac48b497...,09,May,2026,Newark,New Jersey,USA
1,UFC Fight Night: Della Maddalena vs. Prates,http://ufcstats.com/event-details/872b018076f8...,02,May,2026,Perth,Western Australia,Australia

In [81]:
card = []
for i in range(df_events.shape[0]):
    if 'UFC Fight Night' in df_events['event_name'][i]:
        card.append(0)
    else:
        card.append(1)
card

df_events['main_card'] = card

In [83]:
df_events.head(10)

,event_name,event_url,day,month,year,city,region,country,main_card
0,UFC 328: Chimaev vs. Strickland,http://ufcstats.com/event-details/9eedac48b497...,09,May,2026,Newark,New Jersey,USA,1
1,UFC Fight Night: Della Maddalena vs. Prates,http://ufcstats.com/event-details/872b018076f8...,02,May,2026,Perth,Western Australia,Australia,0
2,UFC Fight Night: Sterling vs. Zalal,http://ufcstats.com/event-details/e60d773a0a42...,25,April,2026,Las Vegas,Nevada,USA,0
3,UFC Fight Night: Burns vs. Malott,http://ufcstats.com/event-details/c3ac8d0da7b0...,18,April,2026,Winnipeg,Manitoba,Canada,0
4,UFC 327: Prochazka vs. Ulberg,http://ufcstats.com/event-details/f3eb664db7fb...,11,April,2026,Miami,Florida,USA,1
5,UFC Fight Night: Moicano vs. Duncan,http://ufcstats.com/event-details/9a70f67ad218...,04,April,2026,Las Vegas,Nevada,USA,0
6,UFC Fight Night: Adesanya vs. Pyfer,http://ufcstats.com/event-details/5c38639f860a...,28,March,2026,Seattle,Washington,USA,0
7,UFC Fight Night: Evloev vs. Murphy,http://ufcstats.com/event-details/69108cb8b32e...,21,March,2026,London,England,United Kingdom,0
8,UFC Fight Night: Emmett vs. Vallejos,http://ufcstats.com/event-details/babc6b574533...,14,March,2026,Las Vegas,Nevada,USA,0
9,UFC 326: Holloway vs. Oliveira 2,http://ufcstats.com/event-details/15ec018d1447...,07,March,2026,Las Vegas,Nevada,USA,1

In [91]:
## θα ορίσω ένα μοναδικό κωδικό σε κάθε ένα event ώστε αργότερα να κάνω join  με τους αγώνες που έγιναν στο καθένα,στην προκειμένη τον αριθμό Α/Α

df_events['ID'] = [i for i in range(df_events.shape[0],0,-1)]

In [92]:
df_events = df_events[['ID','event_name','main_card','year','country','month','day','city','region','event_url']]

In [94]:
df_events.tail(10)

,ID,event_name,main_card,year,country,month,day,city,region,event_url
763,10,UFC 10: The Tournament,1,1996,USA,July,12,Birmingham,Alabama,http://ufcstats.com/event-details/aee8eecfc4bf...
764,9,UFC 9: Motor City Madness,1,1996,USA,May,17,Detroit,Michigan,http://ufcstats.com/event-details/a390eb8a9b2d...
765,8,UFC 8: David vs Goliath,1,1996,Puerto Rico,February,16,San Juan,unknown,http://ufcstats.com/event-details/b63e800c18e0...
766,7,UFC - Ultimate Ultimate '95,1,1995,USA,December,16,Denver,Colorado,http://ufcstats.com/event-details/31bbd46d57df...
767,6,UFC 7: The Brawl in Buffalo,1,1995,USA,September,08,Buffalo,New York,http://ufcstats.com/event-details/5af480a3b2e1...
768,5,UFC 6: Clash of the Titans,1,1995,USA,July,14,Casper,Wyoming,http://ufcstats.com/event-details/1c3f5e85b59e...
769,4,UFC 5: The Return of the Beast,1,1995,USA,April,07,Charlotte,North Carolina,http://ufcstats.com/event-details/dedc3bb440d0...
770,3,UFC 4: Revenge of the Warriors,1,1994,USA,December,16,Tulsa,Oklahoma,http://ufcstats.com/event-details/b60391da771d...
771,2,UFC 3: The American Dream,1,1994,USA,September,09,Charlotte,North Carolina,http://ufcstats.com/event-details/1a49e0670dfa...
772,1,UFC 2: No Way Out,1,1994,USA,March,11,Denver,Colorado,http://ufcstats.com/event-details/a6a9ab5a824e...

In [95]:
df_events.to_csv('events.csv',index=False)